# reference: http://www.objc.io/issue-6/travis-ci.html

language: objective-c
script:
- xctool test -workspace Example/3DGridViewController.xcworkspace -scheme 3DGridViewController -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
